# Damn Vulnerable NodeJS Application
# https://github.com/appsecco/dvna

FROM node:carbon
LABEL MAINTAINER "Subash SN"

WORKDIR /app

RUN npm install -g nodemon@1.19.4

CMD ["/bin/bash", "/app/entrypoint-dev.sh"]
