sonar.projectKey=dvna-devsecops
sonar.projectName=dvna-devsecops
sonar.sources=.
sonar.sourceEncoding=UTF-8

# EXCLUSIONS IMPORTANTES (rapports + dépendances + fichiers générés)
sonar.exclusions=**/node_modules/**,**/coverage/**,**/.git/**,**/zap-report.html,**/dependency-check-report.html,**/dependency-check-report.xml,**/checkov-report.json,**/results.json
