sonar.projectKey=dvna-devsecops
sonar.projectName=dvna-devsecops
sonar.sources=.
sonar.sourceEncoding=UTF-8

# EXCLUSIONS IMPORTANTES (évite le crash mémoire)
sonar.exclusions=node_modules/**,coverage/**,.git/**,dependency-check-report.html